.TH FREESWEEP 6 "Version 0.86" "Gus Hartmann & Pete Keller"

.SH NAME
freesweep \- a curses minesweeper-style game

.SH SYNOPSIS
.TP 6
\fBfreesweep\fP [\fI-% percent\fP] [\fI-a\fP] [\fI-b\fP] [\fI-d\fP] [\fI-f\fP] [\fI-g\fP] [\fI-h height\fP]
[\fI-i\fP] [\fI-m mines\fP] [\fI-s\fP] [\fI-v\fP] [\fI-w width\fP]

.SH DESCRIPTION
\fBfreesweep\fP is a curses-based minesweeper game for *nix.

.SH FILES
.TP 10
.I ~/.sweeprc
The user's sweep resource file.
.TP 10
.I ~/.sweeptimes
The user's sweep best times file.
.TP 10
.I PREFIX/etc/sweeprc
The global default sweep resource file.

.SH AUTHORS
Gus Hartmann <hartmann@upl.cs.wisc.edu>
.br
Pete Keller <psilord@upl.cs.wisc.edu>
.br

.SH CREDITS
This program would not have been written had there been more machines capable
of running X Windows in the lab where I learned to program, the
.I Undergraduate Project Lab
at the
.I University of Wisconsin Department of Computer Sciences

